BLOCK_STATES = {
    "age": {"range": [0, 25], "type": "byte"},
    "attached": {"type": "boolean", "values": [True, False]},
    "attachment": {"type": "string", "values": ["ceiling", "double_wall", "floor", "single_wall"]},
    "axis": {"type": "string", "values": ["x", "y", "z"]},
    "berries": {"type": "boolean", "values": [True, False]},
    "bites": {"range": [0, 6], "type": "byte"},
    "bloom": {"type": "boolean", "values": [True, False]},
    "bottom": {"type": "boolean", "values": [True, False]},
    "can_summon": {"type": "boolean", "values": [True, False]},
    "charges": {"range": [0, 4], "type": "byte"},
    "conditional": {"type": "boolean", "values": [True, False]},
    "delay": {"range": [1, 4], "type": "byte"},
    "disarmed": {"type": "boolean", "values": [True, False]},
    "distance": {"range": [0, 7], "type": "byte"},
    "down": {"type": "boolean", "values": [True, False]},
    "drag": {"type": "boolean", "values": [True, False]},
    "east": {"type": "string", "values": [True, False, "low", "none", "tall"]},
    "eggs": {"range": [1, 4], "type": "byte"},
    "enabled": {"type": "boolean", "values": [True, False]},
    "extended": {"type": "boolean", "values": [True, False]},
    "eye": {"type": "boolean", "values": [True, False]},
    "face": {"type": "string", "values": ["ceiling", "floor", "wall"]},
    "facing": {"type": "string", "values": ["down", "east", "north", "south", "up", "west"]},
    "half": {"type": "string", "values": ["bottom", "lower", "top", "upper"]},
    "hanging": {"type": "boolean", "values": [True, False]},
    "has_book": {"type": "boolean", "values": [True, False]},
    "has_bottle_0": {"type": "boolean", "values": [True, False]},
    "has_bottle_1": {"type": "boolean", "values": [True, False]},
    "has_bottle_2": {"type": "boolean", "values": [True, False]},
    "has_record": {"type": "boolean", "values": [True, False]},
    "hatch": {"range": [0, 2], "type": "byte"},
    "hinge": {"type": "string", "values": ["left", "right"]},
    "honey_level": {"range": [0, 5], "type": "byte"},
    "in_wall": {"type": "boolean", "values": [True, False]},
    "instrument": {"type": "string",
                   "values": ["banjo", "basedrum", "bass", "bell", "bit", "chime", "cow_bell", "creeper", "custom_head",
                              "didgeridoo", "dragon", "flute", "guitar", "harp", "hat", "iron_xylophone", "piglin",
                              "pling", "skeleton", "snare", "wither_skeleton", "xylophone", "zombie"]},
    "layers": {"range": [1, 8], "type": "byte"},
    "leaves": {"type": "string", "values": ["large", "none", "small"]},
    "level": {"range": [0, 15], "type": "byte"},
    "lit": {"type": "boolean", "values": [True, False]},
    "locked": {"type": "boolean", "values": [True, False]},
    "mode": {"type": "string", "values": ["compare", "corner", "data", "load", "save", "subtract"]},
    "moisture": {"range": [0, 7], "type": "byte"},
    "north": {"type": "string", "values": [True, False, "low", "none", "tall"]},
    "note": {"range": [0, 24], "type": "byte"},
    "occupied": {"type": "boolean", "values": [True, False]},
    "open": {"type": "boolean", "values": [True, False]},
    "orientation": {"type": "string",
                    "values": ["down_east", "down_north", "down_south", "down_west", "east_up", "north_up", "south_up",
                               "up_east", "up_north", "up_south", "up_west", "west_up"]},
    "part": {"type": "string", "values": ["foot", "head"]},
    "persistent": {"type": "boolean", "values": [True, False]},
    "pickles": {"range": [1, 4], "type": "byte"},
    "power": {"range": [0, 15], "type": "byte"},
    "powered": {"type": "boolean", "values": [True, False]},
    "rotation": {"range": [0, 15], "type": "byte"},
    "sculk_sensor_phase": {"type": "string", "values": ["active", "cooldown", "inactive"]},
    "shape": {"type": "string",
              "values": ["ascending_east", "ascending_north", "ascending_south", "ascending_west", "east_west",
                         "inner_left", "inner_right", "north_east", "north_south", "north_west", "outer_left",
                         "outer_right", "south_east", "south_west", "straight"]},
    "shrieking": {"type": "boolean", "values": [True, False]},
    "signal_fire": {"type": "boolean", "values": [True, False]},
    "slot_0_occupied": {"type": "boolean", "values": [True, False]},
    "slot_1_occupied": {"type": "boolean", "values": [True, False]},
    "slot_2_occupied": {"type": "boolean", "values": [True, False]},
    "slot_3_occupied": {"type": "boolean", "values": [True, False]},
    "slot_4_occupied": {"type": "boolean", "values": [True, False]},
    "slot_5_occupied": {"type": "boolean", "values": [True, False]},
    "snowy": {"type": "boolean", "values": [True, False]},
    "south": {"type": "string", "values": [True, False, "low", "none", "tall"]},
    "stage": {"range": [0, 1], "type": "byte"},
    "thickness": {"type": "string", "values": ["base", "frustum", "middle", "tip", "tip_merge"]},
    "tilt": {"type": "string", "values": ["full", "none", "partial", "unstable"]},
    "triggered": {"type": "boolean", "values": [True, False]},
    "type": {"type": "string", "values": ["bottom", "double", "left", "normal", "right", "single", "sticky", "top"]},
    "unstable": {"type": "boolean", "values": [True, False]},
    "up": {"type": "boolean", "values": [True, False]},
    "vertical_direction": {"type": "string", "values": ["down", "up"]},
    "waterlogged": {"type": "boolean", "values": [True, False]},
    "west": {"type": "string", "values": [True, False, "low", "none", "tall"]}
}
